name: release

on:
    push:
        tags:
            - "v*"

jobs:
    release:
        runs-on: "ubuntu-latest"
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: "16.x"
                  registry-url: "https://npm.pkg.github.com"
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: npm ci
              run: npm ci

            - name: Build Code
              run: npm run build_lib

            - name: Pack and publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  npm run github:release
